/*
 *  This file was generated by the SOM Compiler and Emitter Framework.
 *  Generated using template emitter:
 *      SOM Emitter emitctm: 2.23.1.9
 */

#ifndef SOM_Module_practicebitmap_Source
#define SOM_Module_practicebitmap_Source
#endif
#define PracticeBitmap_Class_Source
#define M_PracticeBitmap_Class_Source

#include "PracticeBitmap.ih"


SOM_Scope ULONG  SOMLINK PracticeBitmapX_wpQueryDefaultView(PracticeBitmap *somSelf)
{
    ULONG ancestorView;

    PracticeBitmapMethodDebug("PracticeBitmap","PracticeBitmapX_wpQueryDefaultView");

    ancestorView = MMBitmap_parent_WPBitmap_wpQueryDefaultView(somSelf);

    if (ancestorView != OPEN_SETTINGS)
      return (ancestorView);

    return (PracticeBitmap_parent_MMBitmap_wpQueryDefaultView(somSelf));
}

SOM_Scope HPOINTER  SOMLINK PracticeBitmapX_wpQueryAssociatedFileIcon(PracticeBitmap *somSelf)
{
    PracticeBitmapMethodDebug("PracticeBitmap","PracticeBitmapX_wpQueryAssociatedFileIcon");

    return (NULLHANDLE);
}


SOM_Scope ULONG  SOMLINK PracticeBitmapX_wpclsQueryDefaultView(M_PracticeBitmap *somSelf)
{
    ULONG ancestorView;

    M_PracticeBitmapMethodDebug("M_PracticeBitmap","PracticeBitmapX_wpclsQueryDefaultView");

    ancestorView = M_MMBitmap_parent_M_WPBitmap_wpclsQueryDefaultView(somSelf);

    if (ancestorView != OPEN_SETTINGS)
      return (ancestorView);

    return (M_PracticeBitmap_parent_M_MMBitmap_wpclsQueryDefaultView(somSelf));
}

SOM_Scope PSZ  SOMLINK PracticeBitmapX_wpclsQueryTitle(M_PracticeBitmap *somSelf)
{
    static char title[256] = "Practice Bitmap";

    M_PracticeBitmapMethodDebug("M_PracticeBitmap","PracticeBitmapX_wpclsQueryTitle");

    return (title);
}

