
/*
 * This file was generated by the SOM Compiler.
 * FileName: F:\PRACTICE\QuickFlick\SourcePM\PracticeMooV.h.
 * Generated using:
 *     SOM Precompiler somipc: 2.29.1.17
 *     SOM Emitter emith: 2.47
 */

#ifndef SOM_PracticeMooV_h
#define SOM_PracticeMooV_h


/*
 * Passthru lines: File: "C.h", "before"
 */


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef PracticeMooV
#define PracticeMooV SOMObject
#endif
#include <mmmov.h>

/*
 * Start of bindings for IDL types
 */

#ifndef SOMClass
    #define SOMClass SOMObject
#endif /* SOMClass */
#ifndef WPFolder
    #define WPFolder SOMObject
#endif /* WPFolder */
#ifndef M_WPObject
    #define M_WPObject SOMObject
#endif /* M_WPObject */
#ifndef WPObject
    #define WPObject SOMObject
#endif /* WPObject */
#ifndef WPImageFile
    #define WPImageFile SOMObject
#endif /* WPImageFile */
#ifndef M_WPFileSystem
    #define M_WPFileSystem SOMObject
#endif /* M_WPFileSystem */
#ifndef M_WPDataFile
    #define M_WPDataFile SOMObject
#endif /* M_WPDataFile */
#ifndef M_MMDataFile
    #define M_MMDataFile SOMObject
#endif /* M_MMDataFile */
#ifndef M_MMVideo
    #define M_MMVideo SOMObject
#endif /* M_MMVideo */
#ifndef M_MMMOV
    #define M_MMMOV SOMObject
#endif /* M_MMMOV */
#ifndef M_PracticeMooV
    #define M_PracticeMooV SOMObject
#endif /* M_PracticeMooV */

/*
 * End of bindings for IDL types.
 */

#define PracticeMooV_MajorVersion 1
#define PracticeMooV_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define PracticeMooVNewClass PracticeMooVc
#pragma linkage(PracticeMooVc, system)
#define PracticeMooVClassData PracticeMooVd
#define PracticeMooVCClassData PracticeMooVx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define PracticeMooV_classObj PracticeMooVClassData.classObject
#define _PracticeMooV PracticeMooV_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK PracticeMooVNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(PracticeMooVNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct PracticeMooVClassDataStructure {
	SOMClass *classObject;
} SOMDLINK PracticeMooVClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct PracticeMooVCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK PracticeMooVCClassData;

/*
 * New and Renew macros for PracticeMooV
 */
#define PracticeMooVNew() \
   ( _PracticeMooV ? \
	_somNew(_PracticeMooV) \
	: ( PracticeMooVNewClass(\
		PracticeMooV_MajorVersion, \
		PracticeMooV_MinorVersion),\
	   _somNew(_PracticeMooV)))
#define PracticeMooVRenew(buf) \
   ( _PracticeMooV ? \
	_somRenew(_PracticeMooV, buf) \
	: ( PracticeMooVNewClass(\
		PracticeMooV_MajorVersion, \
		PracticeMooV_MinorVersion),\
	   _somRenew(_PracticeMooV, buf)))

/*
 * Override method: wpQueryDefaultView
 */
#define PracticeMooV_wpQueryDefaultView(somSelf) \
	WPObject_wpQueryDefaultView(somSelf)

/*
 * Override method: wpQueryAssociatedFileIcon
 */
#define PracticeMooV_wpQueryAssociatedFileIcon(somSelf) \
	WPDataFile_wpQueryAssociatedFileIcon(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define PracticeMooV_wpFormatDragItem WPObject_wpFormatDragItem
#define PracticeMooV_wpMenuItemSelected WPObject_wpMenuItemSelected
#define PracticeMooV_wpModifyPopupMenu WPObject_wpModifyPopupMenu
#define PracticeMooV_wpOpen WPObject_wpOpen
#define PracticeMooV_wpUnInitData WPObject_wpUnInitData
#define PracticeMooV_wpFilterPopupMenu WPObject_wpFilterPopupMenu
#define PracticeMooV_wpInitData WPObject_wpInitData
#define PracticeMooV_wpMenuItemHelpSelected WPObject_wpMenuItemHelpSelected
#define PracticeMooV_wpQueryConcurrentView WPObject_wpQueryConcurrentView
#define PracticeMooV_wpSetTitle WPObject_wpSetTitle
#define PracticeMooV_wpSetup WPObject_wpSetup
#define PracticeMooV_wpObjectReady WPObject_wpObjectReady
#define PracticeMooV_wpAddBecomePage WPDataFile_wpAddBecomePage
#define PracticeMooV_wpAddFileTypePage WPDataFile_wpAddFileTypePage
#define PracticeMooV_wpPrintMetaFile WPDataFile_wpPrintMetaFile
#define PracticeMooV_wpPrintPifFile WPDataFile_wpPrintPifFile
#define PracticeMooV_wpPrintPrinterSpecificFile WPDataFile_wpPrintPrinterSpecificFile
#define PracticeMooV_wpPrintUnknownFile WPDataFile_wpPrintUnknownFile
#define PracticeMooV_wpQueryAssociatedProgram WPDataFile_wpQueryAssociatedProgram
#define PracticeMooV_wpSetAssociatedFileIcon WPDataFile_wpSetAssociatedFileIcon
#define PracticeMooV_wpSetContentsFromPointer WPDataFile_wpSetContentsFromPointer
#define PracticeMooV_wpQueryPointerFromContents WPDataFile_wpQueryPointerFromContents
#define PracticeMooV_wpSetContentsFromHandle WPDataFile_wpSetContentsFromHandle
#define PracticeMooV_wpQueryHandleFromContents WPDataFile_wpQueryHandleFromContents
#define PracticeMooV_wpRenderFromClipboard WPDataFile_wpRenderFromClipboard
#define PracticeMooV_wpDragOver WPObject_wpDragOver
#define PracticeMooV_wpRestoreState WPObject_wpRestoreState
#define PracticeMooV_wpSetDefaultView WPObject_wpSetDefaultView
#define PracticeMooV_wpSetRealName WPFileSystem_wpSetRealName
#define PracticeMooV_wpSetType WPFileSystem_wpSetType
#define PracticeMooV_wpAddSettingsPages WPObject_wpAddSettingsPages
#define PracticeMooV_wpAddObjectWindowPage WPObject_wpAddObjectWindowPage
#define PracticeMooV_wpPrintObject WPObject_wpPrintObject
#define PracticeMooV_wpModifyMenu WPObject_wpModifyMenu
#define PracticeMooV_wpQueryDefaultHelp WPObject_wpQueryDefaultHelp
#define PracticeMooV_wpConfirmRenameFileWithExt WPFileSystem_wpConfirmRenameFileWithExt
#define PracticeMooV_wpQueryIcon WPObject_wpQueryIcon
#define PracticeMooV_wpRender WPObject_wpRender
#define PracticeMooV_somDefaultInit SOMObject_somDefaultInit
#define PracticeMooV_somDestruct SOMObject_somDestruct
#define PracticeMooV_wpConfirmKeepAssoc WPFileSystem_wpConfirmKeepAssoc
#define PracticeMooV_wpQueryType WPFileSystem_wpQueryType
#define PracticeMooV_wpSetAttr WPFileSystem_wpSetAttr
#define PracticeMooV_wpQueryAttr WPFileSystem_wpQueryAttr
#define PracticeMooV_wpAddFile1Page WPFileSystem_wpAddFile1Page
#define PracticeMooV_wpAddFile2Page WPFileSystem_wpAddFile2Page
#define PracticeMooV_wpAddFile3Page WPFileSystem_wpAddFile3Page
#define PracticeMooV_wpAddFileMenuPage WPFileSystem_wpAddFileMenuPage
#define PracticeMooV_wpQueryCreation WPFileSystem_wpQueryCreation
#define PracticeMooV_wpQueryLastAccess WPFileSystem_wpQueryLastAccess
#define PracticeMooV_wpQueryLastWrite WPFileSystem_wpQueryLastWrite
#define PracticeMooV_wpQueryFileSize WPFileSystem_wpQueryFileSize
#define PracticeMooV_wpQueryEASize WPFileSystem_wpQueryEASize
#define PracticeMooV_wpSetDateInfo WPFileSystem_wpSetDateInfo
#define PracticeMooV_wpSetFileSizeInfo WPFileSystem_wpSetFileSizeInfo
#define PracticeMooV_wpRefresh WPFileSystem_wpRefresh
#define PracticeMooV_wpQueryRefreshFlags WPFileSystem_wpQueryRefreshFlags
#define PracticeMooV_wpSetRefreshFlags WPFileSystem_wpSetRefreshFlags
#define PracticeMooV_wpPrintPlainTextFile WPFileSystem_wpPrintPlainTextFile
#define PracticeMooV_wpSetTitleAndRenameFile WPFileSystem_wpSetTitleAndRenameFile
#define PracticeMooV_wpVerifyUpdateAccess WPFileSystem_wpVerifyUpdateAccess
#define PracticeMooV_wpQueryEASupport WPFileSystem_wpQueryEASupport
#define PracticeMooV_wpAddUserItemsToPopupMenu WPFileSystem_wpAddUserItemsToPopupMenu
#define PracticeMooV_wpIsDiskSwapped WPFileSystem_wpIsDiskSwapped
#define PracticeMooV_wpQueryRealName WPFileSystem_wpQueryRealName
#define PracticeMooV_wpQueryFilename WPFileSystem_wpQueryFilename
#define PracticeMooV_wpQueryDisk WPFileSystem_wpQueryDisk
#define PracticeMooV_wpQueryDateInfo WPFileSystem_wpQueryDateInfo
#define PracticeMooV_wpQueryHandle WPObject_wpQueryHandle
#define PracticeMooV_wpSaveImmediate WPObject_wpSaveImmediate
#define PracticeMooV_wpViewObject WPObject_wpViewObject
#define PracticeMooV_wpSwitchTo WPObject_wpSwitchTo
#define PracticeMooV_wpCopyObject WPObject_wpCopyObject
#define PracticeMooV_wpCreateFromTemplate WPObject_wpCreateFromTemplate
#define PracticeMooV_wpMoveObject WPObject_wpMoveObject
#define PracticeMooV_wpQueryIconData WPObject_wpQueryIconData
#define PracticeMooV_wpSetIconData WPObject_wpSetIconData
#define PracticeMooV_wpQueryDetailsData WPObject_wpQueryDetailsData
#define PracticeMooV_wpSaveState WPObject_wpSaveState
#define PracticeMooV_wpDraggedOverObject WPObject_wpDraggedOverObject
#define PracticeMooV_wpDroppedOnObject WPObject_wpDroppedOnObject
#define PracticeMooV_wpQueryNameClashOptions WPObject_wpQueryNameClashOptions
#define PracticeMooV_wpAppendObject WPObject_wpAppendObject
#define PracticeMooV_wpReplaceObject WPObject_wpReplaceObject
#define PracticeMooV_wpQueryStyle WPObject_wpQueryStyle
#define PracticeMooV_wpFilterMenu WPObject_wpFilterMenu
#define PracticeMooV_wpDoesObjectMatch WPObject_wpDoesObjectMatch
#define PracticeMooV_wpIdentify WPObject_wpIdentify
#define PracticeMooV_wpIsDeleteable WPObject_wpIsDeleteable
#define PracticeMooV_wpAddObjectGeneralPage WPObject_wpAddObjectGeneralPage
#define PracticeMooV_wpAddObjectGeneralPage2 WPObject_wpAddObjectGeneralPage2
#define PracticeMooV_wpAddToObjUseList WPObject_wpAddToObjUseList
#define PracticeMooV_wpAllocMem WPObject_wpAllocMem
#define PracticeMooV_wpAssertObjectMutexSem WPObject_wpAssertObjectMutexSem
#define PracticeMooV_wpClose WPObject_wpClose
#define PracticeMooV_wpCnrInsertObject WPObject_wpCnrInsertObject
#define PracticeMooV_wpCnrRemoveObject WPObject_wpCnrRemoveObject
#define PracticeMooV_wpCnrSetEmphasis WPObject_wpCnrSetEmphasis
#define PracticeMooV_wpConfirmDelete WPObject_wpConfirmDelete
#define PracticeMooV_wpConfirmObjectTitle WPObject_wpConfirmObjectTitle
#define PracticeMooV_wpCopiedFromTemplate WPObject_wpCopiedFromTemplate
#define PracticeMooV_wpCreateAnother WPObject_wpCreateAnother
#define PracticeMooV_wpCreateShadowObject WPObject_wpCreateShadowObject
#define PracticeMooV_wpDelete WPObject_wpDelete
#define PracticeMooV_wpDeleteFromObjUseList WPObject_wpDeleteFromObjUseList
#define PracticeMooV_wpDisplayHelp WPObject_wpDisplayHelp
#define PracticeMooV_wpDisplayMenu WPObject_wpDisplayMenu
#define PracticeMooV_wpDrop WPObject_wpDrop
#define PracticeMooV_wpEndConversation WPObject_wpEndConversation
#define PracticeMooV_wpFindUseItem WPObject_wpFindUseItem
#define PracticeMooV_wpFree WPObject_wpFree
#define PracticeMooV_wpFreeMem WPObject_wpFreeMem
#define PracticeMooV_wpHide WPObject_wpHide
#define PracticeMooV_wpInsertPopupMenuItems WPObject_wpInsertPopupMenuItems
#define PracticeMooV_wpInsertMenuItems WPObject_wpInsertMenuItems
#define PracticeMooV_wpInsertSettingsPage WPObject_wpInsertSettingsPage
#define PracticeMooV_wpQueryButtonAppearance WPObject_wpQueryButtonAppearance
#define PracticeMooV_wpQueryConfirmations WPObject_wpQueryConfirmations
#define PracticeMooV_wpQueryError WPObject_wpQueryError
#define PracticeMooV_wpSetFolder WPObject_wpSetFolder
#define PracticeMooV_wpQueryFolder WPObject_wpQueryFolder
#define PracticeMooV_wpQueryMinWindow WPObject_wpQueryMinWindow
#define PracticeMooV_wpSetTaskRec WPObject_wpSetTaskRec
#define PracticeMooV_wpFindTaskRec WPObject_wpFindTaskRec
#define PracticeMooV_wpQueryTitle WPObject_wpQueryTitle
#define PracticeMooV_wpRegisterView WPObject_wpRegisterView
#define PracticeMooV_wpReleaseObjectMutexSem WPObject_wpReleaseObjectMutexSem
#define PracticeMooV_wpRenderComplete WPObject_wpRenderComplete
#define PracticeMooV_wpRequestObjectMutexSem WPObject_wpRequestObjectMutexSem
#define PracticeMooV_wpRestore WPObject_wpRestore
#define PracticeMooV_wpRestoreData WPObject_wpRestoreData
#define PracticeMooV_wpRestoreLong WPObject_wpRestoreLong
#define PracticeMooV_wpRestoreString WPObject_wpRestoreString
#define PracticeMooV_wpSaveData WPObject_wpSaveData
#define PracticeMooV_wpSaveDeferred WPObject_wpSaveDeferred
#define PracticeMooV_wpSaveLong WPObject_wpSaveLong
#define PracticeMooV_wpSaveString WPObject_wpSaveString
#define PracticeMooV_wpScanSetupString WPObject_wpScanSetupString
#define PracticeMooV_wpSetConcurrentView WPObject_wpSetConcurrentView
#define PracticeMooV_wpSetButtonAppearance WPObject_wpSetButtonAppearance
#define PracticeMooV_wpSetDefaultHelp WPObject_wpSetDefaultHelp
#define PracticeMooV_wpSetError WPObject_wpSetError
#define PracticeMooV_wpQueryScreenGroupID WPObject_wpQueryScreenGroupID
#define PracticeMooV_wpSetupOnce WPObject_wpSetupOnce
#define PracticeMooV_wpSetIcon WPObject_wpSetIcon
#define PracticeMooV_wpSetMinWindow WPObject_wpSetMinWindow
#define PracticeMooV_wpModifyStyle WPObject_wpModifyStyle
#define PracticeMooV_wpQueryTrueStyle WPObject_wpQueryTrueStyle
#define PracticeMooV_wpUnlockObject WPObject_wpUnlockObject
#define PracticeMooV_wpIsObjectInitialized WPObject_wpIsObjectInitialized
#define PracticeMooV_wpCreateShadowObjectExt WPObject_wpCreateShadowObjectExt
#define PracticeMooV_wpCnrDeleteUseItem WPObject_wpCnrDeleteUseItem
#define PracticeMooV_wpQueryCoreRecord WPObject_wpQueryCoreRecord
#define PracticeMooV_wpSetObjectID WPObject_wpSetObjectID
#define PracticeMooV_wpQueryObjectID WPObject_wpQueryObjectID
#define PracticeMooV_wpSetDefaultIconPos WPObject_wpSetDefaultIconPos
#define PracticeMooV_wpQueryDefaultIconPos WPObject_wpQueryDefaultIconPos
#define PracticeMooV_wpCnrRefreshDetails WPObject_wpCnrRefreshDetails
#define PracticeMooV_wpFindViewItem WPObject_wpFindViewItem
#define PracticeMooV_wpLockObject WPObject_wpLockObject
#define PracticeMooV_wpIsLocked WPObject_wpIsLocked
#define PracticeMooV_wpQueryContainerFlagPtr WPObject_wpQueryContainerFlagPtr
#define PracticeMooV_wpWaitForClose WPObject_wpWaitForClose
#define PracticeMooV_wpSetMenuStyle WPObject_wpSetMenuStyle
#define PracticeMooV_wpQueryMenuStyle WPObject_wpQueryMenuStyle
#define PracticeMooV_wpSetStyle WPObject_wpSetStyle
#define PracticeMooV_somInit SOMObject_somInit
#define PracticeMooV_somUninit SOMObject_somUninit
#define PracticeMooV_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define PracticeMooV_somDefaultAssign SOMObject_somDefaultAssign
#define PracticeMooV_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define PracticeMooV_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define PracticeMooV_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define PracticeMooV_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define PracticeMooV_somDefaultVAssign SOMObject_somDefaultVAssign
#define PracticeMooV_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define PracticeMooV_somFree SOMObject_somFree
#define PracticeMooV_somGetClass SOMObject_somGetClass
#define PracticeMooV_somGetClassName SOMObject_somGetClassName
#define PracticeMooV_somGetSize SOMObject_somGetSize
#define PracticeMooV_somIsA SOMObject_somIsA
#define PracticeMooV_somIsInstanceOf SOMObject_somIsInstanceOf
#define PracticeMooV_somRespondsTo SOMObject_somRespondsTo
#define PracticeMooV_somDispatch SOMObject_somDispatch
#define PracticeMooV_somClassDispatch SOMObject_somClassDispatch
#define PracticeMooV_somCastObj SOMObject_somCastObj
#define PracticeMooV_somResetObj SOMObject_somResetObj
#define PracticeMooV_somDispatchV SOMObject_somDispatchV
#define PracticeMooV_somDispatchL SOMObject_somDispatchL
#define PracticeMooV_somDispatchA SOMObject_somDispatchA
#define PracticeMooV_somDispatchD SOMObject_somDispatchD
#define PracticeMooV_somPrintSelf SOMObject_somPrintSelf
#define PracticeMooV_somDumpSelf SOMObject_somDumpSelf
#define PracticeMooV_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_PracticeMooV_h */

#ifndef SOM_M_PracticeMooV_h
#define SOM_M_PracticeMooV_h


#include <som.h>

/*
 * -- This emitter treats Method Tokens as Thunks by default.
 * -- Use the sc modifier "nothunks" to change this default
 */
#undef somresolve_
#define somresolve_(obj,mToken) ((somMethodProc*)((void)obj, mToken))

/*
 * Define the class name as an object type
 */
#ifndef M_PracticeMooV
#define M_PracticeMooV SOMObject
#endif
#include <mmmov.h>

/*
 * Start of bindings for IDL types
 */


/*
 * End of bindings for IDL types.
 */

#define M_PracticeMooV_MajorVersion 1
#define M_PracticeMooV_MinorVersion 1

/*
 * External name shortening if required
 */
#ifdef SOM_USE_SHORT_EXTERNAL_NAMES
#define M_PracticeMooVNewClass PracticeMooVc
#pragma linkage(PracticeMooVc, system)
#define M_PracticeMooVClassData PracticeMooVd
#define M_PracticeMooVCClassData PracticeMooVx
#endif /* SOM_USE_SHORT_EXTERNAL_NAMES */
/*--------------Migration------------*/
#define M_PracticeMooV_classObj M_PracticeMooVClassData.classObject
#define _M_PracticeMooV M_PracticeMooV_classObj

/*
 * Declare the class creation procedure
 */
SOMEXTERN SOMClass * SOMLINK M_PracticeMooVNewClass(integer4 somtmajorVersion,
		integer4 somtminorVersion);
#pragma linkage(M_PracticeMooVNewClass, system)

/*
 * Declare the class data structure
 */
SOMEXTERN struct M_PracticeMooVClassDataStructure {
	SOMClass *classObject;
} SOMDLINK M_PracticeMooVClassData;

/*
 * Declare the C specific class data structure
 */
SOMEXTERN struct M_PracticeMooVCClassDataStructure {
	somMethodTabs parentMtab;
	somDToken instanceDataToken;
} SOMDLINK M_PracticeMooVCClassData;

/*
 * New and Renew macros for M_PracticeMooV
 */
#define M_PracticeMooVNew() \
   ( _M_PracticeMooV ? \
	_somNew(_M_PracticeMooV) \
	: ( M_PracticeMooVNewClass(\
		M_PracticeMooV_MajorVersion, \
		M_PracticeMooV_MinorVersion),\
	   _somNew(_M_PracticeMooV)))
#define M_PracticeMooVRenew(buf) \
   ( _M_PracticeMooV ? \
	_somRenew(_M_PracticeMooV, buf) \
	: ( M_PracticeMooVNewClass(\
		M_PracticeMooV_MajorVersion, \
		M_PracticeMooV_MinorVersion),\
	   _somRenew(_M_PracticeMooV, buf)))

/*
 * Override method: wpclsQueryDefaultView
 */
#define M_PracticeMooV_wpclsQueryDefaultView(somSelf) \
	M_WPObject_wpclsQueryDefaultView(somSelf)

/*
 * Override method: wpclsQueryTitle
 */
#define M_PracticeMooV_wpclsQueryTitle(somSelf) \
	M_WPObject_wpclsQueryTitle(somSelf)
#ifndef SOM_DONT_USE_INHERITED_MACROS
#define M_PracticeMooV_wpclsQueryInstanceType M_WPFileSystem_wpclsQueryInstanceType
#define M_PracticeMooV_wpclsQueryInstanceFilter M_WPFileSystem_wpclsQueryInstanceFilter
#define M_PracticeMooV_wpclsInitData M_WPObject_wpclsInitData
#define M_PracticeMooV_wpclsQueryDefaultHelp M_WPObject_wpclsQueryDefaultHelp
#define M_PracticeMooV_wpclsUnInitData M_WPObject_wpclsUnInitData
#define M_PracticeMooV_wpclsQueryIconData M_WPObject_wpclsQueryIconData
#define M_PracticeMooV_wpclsQueryIcon M_WPObject_wpclsQueryIcon
#define M_PracticeMooV_wpclsCreateDefaultTemplates M_WPObject_wpclsCreateDefaultTemplates
#define M_PracticeMooV_wpclsQueryStyle M_WPObject_wpclsQueryStyle
#define M_PracticeMooV_wpclsAddClipboardAssoc M_WPDataFile_wpclsAddClipboardAssoc
#define M_PracticeMooV_wpclsEnumClipboardClasses M_WPDataFile_wpclsEnumClipboardClasses
#define M_PracticeMooV_wpclsQuerySettingsPageSize M_WPObject_wpclsQuerySettingsPageSize
#define M_PracticeMooV_wpclsQueryAwakeObject M_WPFileSystem_wpclsQueryAwakeObject
#define M_PracticeMooV_wpclsFileSysExists M_WPFileSystem_wpclsFileSysExists
#define M_PracticeMooV_wpclsQueryObjectFromPath M_WPFileSystem_wpclsQueryObjectFromPath
#define M_PracticeMooV_wpclsQueryInstanceClass M_WPFileSystem_wpclsQueryInstanceClass
#define M_PracticeMooV_wpclsQueryDetailsInfo M_WPObject_wpclsQueryDetailsInfo
#define M_PracticeMooV_wpclsQuerySearchInfo M_WPObject_wpclsQuerySearchInfo
#define M_PracticeMooV_wpclsQueryExtendedCriteria M_WPObject_wpclsQueryExtendedCriteria
#define M_PracticeMooV_wpclsNew M_WPObject_wpclsNew
#define M_PracticeMooV_wpclsObjectFromHandle M_WPObject_wpclsObjectFromHandle
#define M_PracticeMooV_wpclsMakeAwake M_WPObject_wpclsMakeAwake
#define M_PracticeMooV_wpclsQueryDetails M_WPObject_wpclsQueryDetails
#define M_PracticeMooV_wpclsQueryFolder M_WPObject_wpclsQueryFolder
#define M_PracticeMooV_wpclsFindObjectFirst M_WPObject_wpclsFindObjectFirst
#define M_PracticeMooV_wpclsFindObjectNext M_WPObject_wpclsFindObjectNext
#define M_PracticeMooV_wpclsFindObjectEnd M_WPObject_wpclsFindObjectEnd
#define M_PracticeMooV_wpclsSetError M_WPObject_wpclsSetError
#define M_PracticeMooV_wpclsQueryError M_WPObject_wpclsQueryError
#define M_PracticeMooV_wpclsQueryObject M_WPObject_wpclsQueryObject
#define M_PracticeMooV_wpclsQueryButtonAppearance M_WPObject_wpclsQueryButtonAppearance
#define M_PracticeMooV_wpclsDecUsage M_WPObject_wpclsDecUsage
#define M_PracticeMooV_wpclsIncUsage M_WPObject_wpclsIncUsage
#define M_PracticeMooV_wpclsInsertMultipleObjects M_WPObject_wpclsInsertMultipleObjects
#define M_PracticeMooV_wpclsFindOneObject M_WPObject_wpclsFindOneObject
#define M_PracticeMooV_wpclsSetSettingsPageSize M_WPObject_wpclsSetSettingsPageSize
#define M_PracticeMooV_wpclsSetIconData M_WPObject_wpclsSetIconData
#define M_PracticeMooV_wpclsSetIcon M_WPObject_wpclsSetIcon
#define M_PracticeMooV_wpclsRemoveObjects M_WPObject_wpclsRemoveObjects
#define M_PracticeMooV_somUninit SOMObject_somUninit
#define M_PracticeMooV_somClassReady SOMClass_somClassReady
#define M_PracticeMooV_somNew SOMClass_somNew
#define M_PracticeMooV_somRenew SOMClass_somRenew
#define M_PracticeMooV__get_somDataAlignment SOMClass__get_somDataAlignment
#define M_PracticeMooV__get_somInstanceDataOffsets SOMClass__get_somInstanceDataOffsets
#define M_PracticeMooV__get_somDirectInitClasses SOMClass__get_somDirectInitClasses
#define M_PracticeMooV_somNewNoInit SOMClass_somNewNoInit
#define M_PracticeMooV_somRenewNoInit SOMClass_somRenewNoInit
#define M_PracticeMooV_somRenewNoZero SOMClass_somRenewNoZero
#define M_PracticeMooV_somRenewNoInitNoZero SOMClass_somRenewNoInitNoZero
#define M_PracticeMooV_somAllocate SOMClass_somAllocate
#define M_PracticeMooV_somDeallocate SOMClass_somDeallocate
#define M_PracticeMooV_somInitClass SOMClass_somInitClass
#define M_PracticeMooV_somInitMIClass SOMClass_somInitMIClass
#define M_PracticeMooV_somAddStaticMethod SOMClass_somAddStaticMethod
#define M_PracticeMooV_somAddDynamicMethod SOMClass_somAddDynamicMethod
#define M_PracticeMooV_somOverrideSMethod SOMClass_somOverrideSMethod
#define M_PracticeMooV_somGetApplyStub SOMClass_somGetApplyStub
#define M_PracticeMooV_somGetClassData SOMClass_somGetClassData
#define M_PracticeMooV_somSetClassData SOMClass_somSetClassData
#define M_PracticeMooV_somGetClassMtab SOMClass_somGetClassMtab
#define M_PracticeMooV_somGetInstanceOffset SOMClass_somGetInstanceOffset
#define M_PracticeMooV_somGetInstancePartSize SOMClass_somGetInstancePartSize
#define M_PracticeMooV_somGetInstanceSize SOMClass_somGetInstanceSize
#define M_PracticeMooV_somGetInstanceToken SOMClass_somGetInstanceToken
#define M_PracticeMooV_somGetMemberToken SOMClass_somGetMemberToken
#define M_PracticeMooV_somGetMethodData SOMClass_somGetMethodData
#define M_PracticeMooV_somGetRdStub SOMClass_somGetRdStub
#define M_PracticeMooV_somGetMethodDescriptor SOMClass_somGetMethodDescriptor
#define M_PracticeMooV_somGetMethodIndex SOMClass_somGetMethodIndex
#define M_PracticeMooV_somGetMethodToken SOMClass_somGetMethodToken
#define M_PracticeMooV_somGetName SOMClass_somGetName
#define M_PracticeMooV_somGetNthMethodData SOMClass_somGetNthMethodData
#define M_PracticeMooV_somGetNthMethodInfo SOMClass_somGetNthMethodInfo
#define M_PracticeMooV_somGetNumMethods SOMClass_somGetNumMethods
#define M_PracticeMooV_somGetNumStaticMethods SOMClass_somGetNumStaticMethods
#define M_PracticeMooV_somGetParent SOMClass_somGetParent
#define M_PracticeMooV_somGetParents SOMClass_somGetParents
#define M_PracticeMooV_somGetVersionNumbers SOMClass_somGetVersionNumbers
#define M_PracticeMooV_somFindMethod SOMClass_somFindMethod
#define M_PracticeMooV_somFindMethodOk SOMClass_somFindMethodOk
#define M_PracticeMooV_somFindSMethod SOMClass_somFindSMethod
#define M_PracticeMooV_somFindSMethodOk SOMClass_somFindSMethodOk
#define M_PracticeMooV_somLookupMethod SOMClass_somLookupMethod
#define M_PracticeMooV_somCheckVersion SOMClass_somCheckVersion
#define M_PracticeMooV_somDescendedFrom SOMClass_somDescendedFrom
#define M_PracticeMooV_somSupportsMethod SOMClass_somSupportsMethod
#define M_PracticeMooV_somDefinedMethod SOMClass_somDefinedMethod
#define M_PracticeMooV_somOverrideMtab SOMClass_somOverrideMtab
#define M_PracticeMooV_somDefaultInit SOMObject_somDefaultInit
#define M_PracticeMooV_somDestruct SOMObject_somDestruct
#define M_PracticeMooV_somDefaultCopyInit SOMObject_somDefaultCopyInit
#define M_PracticeMooV_somDefaultAssign SOMObject_somDefaultAssign
#define M_PracticeMooV_somDefaultConstCopyInit SOMObject_somDefaultConstCopyInit
#define M_PracticeMooV_somDefaultVCopyInit SOMObject_somDefaultVCopyInit
#define M_PracticeMooV_somDefaultConstVCopyInit SOMObject_somDefaultConstVCopyInit
#define M_PracticeMooV_somDefaultConstAssign SOMObject_somDefaultConstAssign
#define M_PracticeMooV_somDefaultVAssign SOMObject_somDefaultVAssign
#define M_PracticeMooV_somDefaultConstVAssign SOMObject_somDefaultConstVAssign
#define M_PracticeMooV_somInit SOMObject_somInit
#define M_PracticeMooV_somFree SOMObject_somFree
#define M_PracticeMooV_somGetClass SOMObject_somGetClass
#define M_PracticeMooV_somGetClassName SOMObject_somGetClassName
#define M_PracticeMooV_somGetSize SOMObject_somGetSize
#define M_PracticeMooV_somIsA SOMObject_somIsA
#define M_PracticeMooV_somIsInstanceOf SOMObject_somIsInstanceOf
#define M_PracticeMooV_somRespondsTo SOMObject_somRespondsTo
#define M_PracticeMooV_somDispatch SOMObject_somDispatch
#define M_PracticeMooV_somClassDispatch SOMObject_somClassDispatch
#define M_PracticeMooV_somCastObj SOMObject_somCastObj
#define M_PracticeMooV_somResetObj SOMObject_somResetObj
#define M_PracticeMooV_somDispatchV SOMObject_somDispatchV
#define M_PracticeMooV_somDispatchL SOMObject_somDispatchL
#define M_PracticeMooV_somDispatchA SOMObject_somDispatchA
#define M_PracticeMooV_somDispatchD SOMObject_somDispatchD
#define M_PracticeMooV_somPrintSelf SOMObject_somPrintSelf
#define M_PracticeMooV_somDumpSelf SOMObject_somDumpSelf
#define M_PracticeMooV_somDumpSelfInt SOMObject_somDumpSelfInt
#endif /* SOM_DONT_USE_INHERITED_MACROS */

#endif       /* SOM_M_PracticeMooV_h */
